### ISSUE TITLE
Could not read file. NumberFormatException

### ISSUE THREAD

**Issue by bvn13** [monitorjbl/excel-streaming-reader#107]
https://yadi.sk/d/7N-lbmgA3MGqCM - this one. Read it as described in your project's main page.

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "1 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.unformattedContents(StreamingSheetReader.java:316)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.handleEvent(StreamingSheetReader.java:184)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.getRow(StreamingSheetReader.java:76)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.access$100(StreamingSheetReader.java:37)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.hasNext(StreamingSheetReader.java:370)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.<init>(StreamingSheetReader.java:364)
	at com.monitorjbl.xlsx.impl.StreamingSheetReader.iterator(StreamingSheetReader.java:336)
	at com.monitorjbl.xlsx.impl.StreamingSheet.iterator(StreamingSheet.java:49)
	at ru.bvn13.test.App.main(App.java:96)
```

**Comment by bvn13** [comment]
please commit my pull request

**Comment by bvn13** [comment]
please commit my pull request
