### ISSUE TITLE
Not able get no of columns for one million records

### ISSUE THREAD

**Issue by koushikkolli** [monitorjbl/excel-streaming-reader#162]
Hi

InputStream is = new FileInputStream(file);
Workbook workbook = StreamingReader.builder()
.rowCacheSize(10)
.bufferSize(4096)
.open(is);

	for (Sheet sheet : workbook){
	    System.out.println(sheet.getSheetName());
	    for (Row r : sheet) {
	      for (Cell c : r) {
	       count=count+1;
	      }
	      break;
	    }
	  }
i am using above code for getting no of columns
the code is working fine if data is less but when data is more
getting error
Exception in thread "main" java.lang.NullPointerException
at com.monitorjbl.xlsx.impl.StreamingSheetReader.setFormatString(StreamingSheetReader.java:278)
at com.monitorjbl.xlsx.impl.StreamingSheetReader.handleEvent(StreamingSheetReader.java:150)
at com.monitorjbl.xlsx.impl.StreamingSheetReader.getRow(StreamingSheetReader.java:76)
at com.monitorjbl.xlsx.impl.StreamingSheetReader.access$200(StreamingSheetReader.java:37)
at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.hasNext(StreamingSheetReader.java:412)
at com.monitorjbl.xlsx.impl.StreamingSheetReader$StreamingRowIterator.(StreamingSheetReader.java:406)
at com.monitorjbl.xlsx.impl.StreamingSheetReader.iterator(StreamingSheetReader.java:378)
at com.monitorjbl.xlsx.impl.StreamingSheet.iterator(StreamingSheet.java:49)

near for (Row r : sheet)

**Comment by monitorjbl** [comment]
Do you have a worksheet with this happening you can share?
