### ISSUE TITLE
NPE when iterating through rows

### ISSUE THREAD

**Issue by andrei-ivanov** [monitorjbl/excel-streaming-reader#18]
Trying to upgrade to 0.2.10 from 0.2.8, now that #15 was fixed...
java.lang.NullPointerException
	at com.monitorjbl.xlsx.StreamingReader.unformattedContents(StreamingReader.java:216)
	at com.monitorjbl.xlsx.StreamingReader.handleEvent(StreamingReader.java:136)
	at com.monitorjbl.xlsx.StreamingReader.getRow(StreamingReader.java:89)
	at com.monitorjbl.xlsx.StreamingReader.access$400(StreamingReader.java:55)
	at com.monitorjbl.xlsx.StreamingReader$StreamingIterator.hasNext(StreamingReader.java:440)
	at com.monitorjbl.xlsx.StreamingReader$StreamingIterator.<init>(StreamingReader.java:434)
	at com.monitorjbl.xlsx.StreamingReader.iterator(StreamingReader.java:236)

**Comment by monitorjbl** [comment]
Pretty sure #17 addresses this issue. I'm waiting on a unit test for it, I haven't seen a spreadsheet that causes this issue before.

**Comment by monitorjbl** [comment]
Could you try with the latest code? Just merged a PR to address this.

**Comment by andrei-ivanov** [comment]
That NPE is gone, but now I get a NPE because we assume, based on the javadoc of the cell implementations from POI, that getStringCellValue() will not return null.
Even for blank cells it should return an empty string.

**Comment by monitorjbl** [comment]
Ah, I'll get that fixed then.

**Comment by monitorjbl** [comment]
This should be fixed now, can you try with the latest code?

**Comment by andrei-ivanov** [comment]
The tests now pass 😊
Not sure how extensive they are, but it's much better now.

Thanks.
