### ISSUE TITLE
getting org.apache.cxf.interceptor.Fault: org/apache/poi/util/StaxHelper exception

### ISSUE THREAD

**Issue by komal11292** [monitorjbl/excel-streaming-reader#183]
org.apache.cxf.interceptor.Fault: org/apache/poi/util/StaxHelper
	at org.apache.cxf.service.invoker.AbstractInvoker.createFault(AbstractInvoker.java:170)[94:org.apache.cxf.cxf-api:2.7.11]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:136)[94:org.apache.cxf.cxf-api:2.7.11]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)[127:org.apache.cxf.cxf-rt-frontend-jaxrs:2.7.11]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)[127:org.apache.cxf.cxf-rt-frontend-jaxrs:2.7.11]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)[94:org.apache.cxf.cxf-api:2.7.11]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)[94:org.apache.cxf.cxf-api:2.7.11]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)[94:org.apache.cxf.cxf-api:2.7.11]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)[94:org.apache.cxf.cxf-api:2.7.11]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:241)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)[102:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:262)[121:org.apache.cxf.cxf-rt-transports-http:2.7.11]
	at Proxy0a14c28c_bfc0_403e_b0f9_410cdd356ac9.service(Unknown Source)[:]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[116:org.ops4j.pax.web.pax-web-jetty:3.2.9]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[107:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[116:org.ops4j.pax.web.pax-web-jetty:3.2.9]

My pom.xml dependencies are:
<dependency>
			<groupId>com.monitorjbl</groupId>
			<artifactId>xlsx-streamer</artifactId>
			<version>1.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlbeans</groupId>
			<artifactId>xmlbeans</artifactId>
			<version>2.6.0</version>
		</dependency>
		<dependency>
			<groupId>stax</groupId>
			<artifactId>stax-api</artifactId>
			<version>1.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml-schemas</artifactId>
			<version>3.17</version>
		</dependency>

**Comment by komal11292** [comment]
This issue came when i'm deploying my bundle in karaf
