### ISSUE TITLE
Unable to load sheet

### ISSUE THREAD

**Issue by abhilashreddy1289** [monitorjbl/excel-streaming-reader#32]
I am working on this API and when testing I am getting below error   Unable to find sheet at index [0]

[](SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation %28NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.monitorjbl.xlsx.exceptions.MissingSheetException: Unable to find sheet at index [0]
    at com.monitorjbl.xlsx.StreamingReader$Builder.read(StreamingReader.java:434)
    at com.monitorjbl.xlsx.StreamingReader$Builder.read(StreamingReader.java:393)
    at test.XLSXToCSVConverterStreamer.xlsx(XLSXToCSVConverterStreamer.java:53)
    at test.XLSXToCSVConverterStreamer.main(XLSXToCSVConverterStreamer.java:160)
)

**Comment by monitorjbl** [comment]
Closing due to age and lack of information
