### ISSUE TITLE
java.lang.IndexOutOfBoundsException with a workbook 

### ISSUE THREAD

**Issue by sambit19** [monitorjbl/excel-streaming-reader#86]
Hi,

I am trying to read a workbook with multiple sheets in it. The total size of the workbook is around 1.2 GB.  I tested my code with a simple multi-sheet workbook and it worked fine. However with the bigger sheet I am getting this error.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(ArrayList.java:653)
        at java.util.ArrayList.get(ArrayList.java:429)
        at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.loadSheets(StreamingWorkbookReader.java:121)
        at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:104)
        at com.monitorjbl.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:77)
        at com.monitorjbl.xlsx.StreamingReader$Builder.open(StreamingReader.java:228)
        at XLStreamReader.main(XLStreamReader.java:30)

**Comment by alusbars** [comment]
Hi,

FYI
It doesn't work with latest apache POI 3.16. Tested with previous 3.15 with successful iterating through all dataset.

**Comment by monitorjbl** [comment]
I think this is what is being reported in #91 . The cause seems to be that POI returns duplicate sheets for some workbooks but not duplicate properties. I'm not sure what actually causes this to happen, but I was able to work around it by just verifying that the sheet URIs are unique. I pushed the fix to the master branch, can you give it a try with the latest code?
