### ISSUE TITLE
ArrayIndexOutOfBoundException in StreamingWorkbook.getSheet(name) when sheet with that name does not exist

### ISSUE THREAD

**Issue by marmys** [monitorjbl/excel-streaming-reader#94]
version used: 1.1.0

stack trace:
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.monitorjbl.xlsx.impl.StreamingWorkbook.getSheet(StreamingWorkbook.java:85)

**Comment by monitorjbl** [comment]
I believe this is fixed in the [latest code](https://github.com/monitorjbl/excel-streaming-reader/blob/master/src/main/java/com/monitorjbl/xlsx/impl/StreamingWorkbook.java#L106), can you check it out and install it locally?

**Comment by marmys** [comment]
Hi, thanks for reply. 
In the latest code throwing ArrayIndexOutOfBoundException is fixed.
But another problem is that now MissingSheetException is thrown when sheet is missing and according to documentation null should be returned.
